### ISSUE TITLE
HMR pug files?

### ISSUE THREAD

**Issue by bastienff** [willyelm/pug-html-loader#13]
I managed to transpile the pug files and split them into a build folder but hmr is not working.

Any idea how make this work with hmr?

**Comment by mryoshio** [comment]
In my case, it resolved when changed webpack-dev-server option.

```
# package.json
-    "start": "webpack-dev-server --hot --inline --progress --colors --watch --content-base dist"
+    "start": "webpack-dev-server --inline --progress --colors --watch --content-base dist"
```

**Comment by kuguarpwnz** [comment]
@bastienff #18 maybe it will help you. try update to 1.1.0 version
