### ISSUE TITLE
v1.1.1 puts a '|' in front of the HTML, causing errors in webpack

### ISSUE THREAD

**Issue by ghost** [willyelm/pug-html-loader#25]
Here's a sample error message.

```
...-component.pug Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <div ...
```

Undoing this change made everything work for me locally: https://github.com/willyelm/pug-html-loader/commit/cca8eb12407bb9297f43750752a9dd6adc844379#diff-6d186b954a58d5bb740f73d84fe39073

Is there something else I need to do to make it work with v1.1.1?

For now, I rolled back to v1.1.0.

**Comment by willyelm** [comment]
Please use raw loader in order to get the content string:

```javascript
module.exports = {
  // your config settings ...
  module: [
    // your modules...
    loaders: [{
      include: /\.pug/,
      loader: ['raw-loader', 'pug-html-loader']
    }]
  ]
};
```

**Comment by WindMay** [comment]
@willyelm That worked for me but use loaders instead of loader to avoid a crash xD

```
loaders: ['raw-loader', 'pug-html-loader']
```

**Comment by ghost** [comment]
Or with my webpack syntax, this:
```
module.exports = {
  module: {
    rules: [{
      test: /\.(jade|pug)$/,
      use: ['raw-loader', 'pug-html-loader']
    }]
  }
}
```

Thanks guys!
