### ISSUE TITLE
webpack2 support?

### ISSUE THREAD

**Issue by rowild** [willyelm/pug-html-loader#31]
The samples still show a "loaders" config object, which webpack2 does not accept (according to my error messages...). Does this package support webpack2? Any chance for a working example? Thanks!

**Comment by stresslimit** [comment]
I'm using with webpack2 with no issues FWIW [with extractTextPlugin btw]. My setup:

```
  module: {
    rules: [
      {
        test: /\.pug$/,
        loader: extractHtml.extract({
          loader: ['html-loader', 'pug-html-loader?pretty&exports=false']
        })
      },
```

**Comment by willyelm** [comment]
@rowild I have tried `rules` and `loaders` both work fine, please give a little more information how does your configuration look like?

**Comment by rowild** [comment]
@willyelm I only used webpack once when I worked along a tutorial form ihatetomatoes. If stuff works with you then please don't bother. Sorry to have wasted your time, but at the moment I discontinue to use webpack.
