### ISSUE TITLE
attributes with sharp symbol

### ISSUE THREAD

**Issue by vovkats** [willyelm/pug-html-loader#34]
@willyelm I can not write sharp attribute.
`e.g.  #staticModal="bs-modal" `
How I understand this loader does not support sharp attributes for pug. Does workaround exist for this case?

**Comment by willyelm** [comment]
Hi @vovkats, please try by added the doctype option:

```javascript
{
  loader: 'pug-html-loader',
  options: {
    doctype: 'html'
  }
}
```

**Comment by vovkats** [comment]
@willyelm Thank you very much. It works with single sharp attribute. Tomorrow I will check work with sharp attribute with value
