### ISSUE TITLE
Pug locals compilation

### ISSUE THREAD

**Issue by var-bp** [willyelm/pug-html-loader#35]
Hello, I have a problem. I need to compile and include another file passed by function. 

```
// index.jade
// I'm using bemto
mixin foo()
  - var blockName = 'some-block' // simplified example
  +b.some-block
    != getBlock(blockName)
+foo()

// some-block.pug
+e.element Some text

// webpack.config.js
use: [
  'html-loader', // without it shows an error
  {
    loader: "pug-html-loader",
    options: {
      data: {
        getBlock: function(blockName) {
          return fs.readFileSync(`${blockName}.pug`, { encoding: 'utf8' });
        },
      }
    }
  }
]
new HtmlWebpackPlugin({
  filename: index.html,
  template: index.pug
})
```
What I get:
```
// index.html
<div class="some-block">+e.element Some text</div>
```

What I need :
```
// index.html
<div class="some-block">
  <div class="some-block__element">Some text</div>
</div>
```
Is this possible? I would be grateful if you help.

**Comment by wiloke1** [comment]
My pugjs config
// webpack.config.js
module.exports = {
	test: /\.(pug|html)$/,
	use: [
		{
			loader: 'file-loader',
			options: {
				name: '[name].html'
			}
		},
		{
			loader: 'pug-html-loader',
			options: {
				pretty: '	',
				exports: false,
				debug: false,
				compileDebug: false,
				cache: true,
				data: {
					require: require
				}
			}
		}
	]
}

**Comment by long-hp** [comment]
My pugjs config
// webpack.config.js

<pre>
<code>module.exports = {
  test: /\.(pug|html)$/,
  use: [
    {
      loader: 'file-loader',
      options: {
        name: '[name].html'
      }
    },
    {
      loader: 'pug-html-loader',
      options: {
        pretty: '  ',
        exports: false,
        debug: false,
        compileDebug: false,
        cache: true,
        data: {
          require: require
        }
      }
    }
  ]
}</code>
</pre>

### entry.js
<pre>
function requireAll(r) {
	r.keys().forEach(r);
}
/**
 * Require all page pug, html
 */

requireAll(require.context('./app/', false, /\.(pug|html)$/));
</pre>
