### ISSUE TITLE
1.0.8 breaks html-loader chain

### ISSUE THREAD

**Issue by hugomarisco** [willyelm/pug-html-loader#4]
I noticed that with version 1.0.8's JSON.stringify when using html-loader after pug-html-loader it can't find any assets src because the quotes are escaped.

I haven't look into a way to go around it, but I'll leave this here for further investigation.

Cheers

**Comment by iboozyvoozy** [comment]
https://github.com/bline/jade-html-loader/issues/19#issuecomment-236876532

**Comment by tscislo** [comment]
+1

**Comment by willyelm** [comment]
this package was originally created to avoid using multiple dependencies in the package and get the template as string, if you are looking html-loader support I think best option would be to use the pug-loader
