### ISSUE TITLE
does pug-html-loader support relative path in img src attr?

### ISSUE THREAD

**Issue by shengxinjing** [willyelm/pug-html-loader#9]
does pug-html-loader support relative path in img src attr?
such as 

```
src
|-- test
|--|-- test.png
|--|--test.jade
webpack.conf.js
```

img in test.jade,when I write 

`img(src="test.png")` it not works 
I hava to write `img(src="src/test/test.png")`

**Comment by chrisnicola** [comment]
This should behave the same as `html-loader` if possible.

**Comment by willyelm** [comment]
this package was originally created to avoid using multiple dependencies in the package and get the template as string, if you are looking html-loader support I think best option would be to use the [pug-loader](https://github.com/pugjs/pug-loader)

**Comment by willyelm** [comment]
to achieve what you want with the latest version you can to use the following configuration:

``` javascript
module.exports = {
  // your config settings ...
  module: [
    // your modules...
    loaders: [{
      test: /\.png$/,
      loader: "url-loader?mimetype=image/png"
    }, {
      test: /\.pug$/,
      loaders: ['html-loader', 'pug-html-loader?exports=false']
    }]
  ]
};
```

**Comment by chrisnicola** [comment]
@willyelm thanks. As for using `pug-loader` that returns a template function unfortunately and even using `apply-loader` in between doesn't seem to work. Probably an issue with `html-loader` to be honest.
